# Generated by Django 4.1.7 on 2023-03-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('catg', models.CharField(max_length=5)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('imgs', models.FileField(upload_to='portfolio')),
            ],
        ),
    ]
