# Generated by Django 4.1.7 on 2023-03-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_portfolio_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='profile')),
                ('bgimg', models.FileField(upload_to='profile')),
            ],
        ),
    ]
